/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcs_1601081023;

import laporan.FormLaporanAnggota;
import laporan.FormLaporanAnggotaPerAnggota;
import laporan.FormLaporanAnggotaPerJekel;
import laporan.FormLaporanBuku;
import laporan.FormLaporanBukuPerTahunTerbit;
import laporan.FormLaporanPeminjaman;
import laporan.FormLaporanPeminjamanPerAnggota;
import laporan.FormLaporanPeminjamanPerBulan;
import view.FormAnggota;
import view.FormBuku;
import view.FormPeminjaman;
import view.FormPengembalian;

/**
 *
 * @author LABP2KOMP11
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuanggota = new javax.swing.JMenuItem();
        menubuku = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        submenupeminjaman = new javax.swing.JMenuItem();
        submenupengembalian = new javax.swing.JMenuItem();
        subMenuAnggotaPerJekel = new javax.swing.JMenu();
        menuPeminjaman = new javax.swing.JMenu();
        subMenuPerAnggota = new javax.swing.JMenuItem();
        subMenuPerBulan = new javax.swing.JMenuItem();
        menuAnggota = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemPerAnggota = new javax.swing.JMenuItem();
        menuBuku = new javax.swing.JMenu();
        subMenuBukuTahunTerbit = new javax.swing.JMenuItem();
        subMenuBukuPengarang = new javax.swing.JMenuItem();
        menuPengembalian = new javax.swing.JMenu();
        subMenuPengembalianAnggota = new javax.swing.JMenuItem();
        subMenuPengembalianBulan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        menuanggota.setText("Anggota");
        menuanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuanggotaActionPerformed(evt);
            }
        });
        menuFile.add(menuanggota);

        menubuku.setText("Buku");
        menubuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubukuActionPerformed(evt);
            }
        });
        menuFile.add(menubuku);

        jMenuBar1.add(menuFile);

        menuTransaksi.setText("Transaksi");

        submenupeminjaman.setText("Peminjaman");
        submenupeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenupeminjamanActionPerformed(evt);
            }
        });
        menuTransaksi.add(submenupeminjaman);

        submenupengembalian.setText("Pengembalian");
        submenupengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenupengembalianActionPerformed(evt);
            }
        });
        menuTransaksi.add(submenupengembalian);

        jMenuBar1.add(menuTransaksi);

        subMenuAnggotaPerJekel.setText("Laporan");
        subMenuAnggotaPerJekel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAnggotaPerJekelActionPerformed(evt);
            }
        });

        menuPeminjaman.setText("Peminjaman");

        subMenuPerAnggota.setText("Per Anggota");
        subMenuPerAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPerAnggotaActionPerformed(evt);
            }
        });
        menuPeminjaman.add(subMenuPerAnggota);

        subMenuPerBulan.setText("Per Bulan");
        subMenuPerBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPerBulanActionPerformed(evt);
            }
        });
        menuPeminjaman.add(subMenuPerBulan);

        subMenuAnggotaPerJekel.add(menuPeminjaman);

        menuAnggota.setText("Anggota");
        menuAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnggotaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Per Jenis Kelamin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAnggota.add(jMenuItem1);

        menuItemPerAnggota.setText("Per Anggota");
        menuItemPerAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPerAnggotaActionPerformed(evt);
            }
        });
        menuAnggota.add(menuItemPerAnggota);

        subMenuAnggotaPerJekel.add(menuAnggota);

        menuBuku.setText("Buku");

        subMenuBukuTahunTerbit.setText("Per Tahun Terbit");
        subMenuBukuTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBukuTahunTerbitActionPerformed(evt);
            }
        });
        menuBuku.add(subMenuBukuTahunTerbit);

        subMenuBukuPengarang.setText("Per Pengarang");
        menuBuku.add(subMenuBukuPengarang);

        subMenuAnggotaPerJekel.add(menuBuku);

        menuPengembalian.setText("Pengembalian");

        subMenuPengembalianAnggota.setText("Per Anggota");
        subMenuPengembalianAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuPengembalianAnggotaActionPerformed(evt);
            }
        });
        menuPengembalian.add(subMenuPengembalianAnggota);

        subMenuPengembalianBulan.setText("Per Bulan");
        menuPengembalian.add(subMenuPengembalianBulan);

        subMenuAnggotaPerJekel.add(menuPengembalian);

        jMenuBar1.add(subMenuAnggotaPerJekel);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuanggotaActionPerformed
        // TODO add your handling code here:
        FormAnggota f = new FormAnggota();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_menuanggotaActionPerformed

    private void subMenuAnggotaPerJekelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAnggotaPerJekelActionPerformed
        // TODO add your handling code here:
        FormLaporanAnggotaPerJekel f = new FormLaporanAnggotaPerJekel();
        f.setVisible(true);
        jDesktopPane1.add(f);
        
    }//GEN-LAST:event_subMenuAnggotaPerJekelActionPerformed

    private void submenupeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenupeminjamanActionPerformed
        // TODO add your handling code here:
        FormPeminjaman f = new FormPeminjaman();
        f.setVisible(true);
        jDesktopPane1.add(f);
       
    }//GEN-LAST:event_submenupeminjamanActionPerformed

    private void subMenuPerBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPerBulanActionPerformed
        // TODO add your handling code here:
         FormLaporanPeminjamanPerBulan f = new FormLaporanPeminjamanPerBulan();
         f.setVisible(true);
         jDesktopPane1.add(f);
    }//GEN-LAST:event_subMenuPerBulanActionPerformed

    private void menuAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnggotaActionPerformed
        // TODO add your handling code here:
        FormLaporanAnggota f=new FormLaporanAnggota();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_menuAnggotaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormLaporanAnggotaPerJekel f =new FormLaporanAnggotaPerJekel();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void subMenuBukuTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuBukuTahunTerbitActionPerformed
        // TODO add your handling code here:
        FormLaporanBukuPerTahunTerbit f= new FormLaporanBukuPerTahunTerbit();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_subMenuBukuTahunTerbitActionPerformed

    private void subMenuPerAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPerAnggotaActionPerformed
        // TODO add your handling code here:
        FormLaporanPeminjamanPerAnggota f= new FormLaporanPeminjamanPerAnggota();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_subMenuPerAnggotaActionPerformed

    private void submenupengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenupengembalianActionPerformed
        // TODO add your handling code here:
        FormPengembalian f = new FormPengembalian();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_submenupengembalianActionPerformed

    private void menubukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubukuActionPerformed
        // TODO add your handling code here
        FormBuku f = new FormBuku();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_menubukuActionPerformed

    private void menuItemPerAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPerAnggotaActionPerformed
        // TODO add your handling code here:
        FormLaporanAnggotaPerAnggota f = new FormLaporanAnggotaPerAnggota();
        f.setVisible(true);
        jDesktopPane1.add(f);
    }//GEN-LAST:event_menuItemPerAnggotaActionPerformed

    private void subMenuPengembalianAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuPengembalianAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuPengembalianAnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAnggota;
    private javax.swing.JMenu menuBuku;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemPerAnggota;
    private javax.swing.JMenu menuPeminjaman;
    private javax.swing.JMenu menuPengembalian;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem menuanggota;
    private javax.swing.JMenuItem menubuku;
    private javax.swing.JMenu subMenuAnggotaPerJekel;
    private javax.swing.JMenuItem subMenuBukuPengarang;
    private javax.swing.JMenuItem subMenuBukuTahunTerbit;
    private javax.swing.JMenuItem subMenuPengembalianAnggota;
    private javax.swing.JMenuItem subMenuPengembalianBulan;
    private javax.swing.JMenuItem subMenuPerAnggota;
    private javax.swing.JMenuItem subMenuPerBulan;
    private javax.swing.JMenuItem submenupeminjaman;
    private javax.swing.JMenuItem submenupengembalian;
    // End of variables declaration//GEN-END:variables
}
